FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y \
      sudo \
      curl \
      vim \
      iproute2 \
      net-tools && \
    pip install --no-cache-dir mitmproxy && \
    apt-get clean

WORKDIR /workspace

EXPOSE 8080 8081

CMD ["mitmweb", "--listen-host", "0.0.0.0", "--web-host", "0.0.0.0"]